integral_lower_limit_label.grid(row = 2, column = 2)
integral_lower_limit_entry = Entry(integral_frame)
integral_lower_limit_entry.grid(row = 3, column = 2)
integral_upper_limit_label = Label(integral_frame, text="Giới hạn trên:")
integral_upper_limit_label.grid(row = 4, column = 2)
integral_upper_limit_entry = Entry(integral_frame)
integral_upper_limit_entry.grid(row = 5, column = 2)
calculate_integral_button = Button(integral_frame, text="Tính", command=calculate_integral)
calculate_integral_button.grid(row = 6, column = 2)
integral_result_label = Label(integral_frame, text="Tích phân: ")
integral_result_label.grid(row = 7, column = 2)

# Frame cho tính giới hạn
limit_frame = Frame(root)
limit_frame.grid(row = 0, column = 3)
limit_label = Label(limit_frame, text="Tính giới hạn (tại một điểm):")
limit_label.grid(row = 0, column = 3)
limit_entry = Entry(limit_frame)
limit_entry.grid(row = 1, column = 3)
limit_point_label = Label(limit_frame, text="Điểm giới hạn:")
limit_point_label.grid(row = 2, column = 3)
limit_point_entry = Entry(limit_frame)
limit_point_entry.grid(row = 3, column = 3)
calculate_limit_button = Button(limit_frame, text="Tính", command=calculate_limit)
calculate_limit_button.grid(row = 4, column = 3)
limit_result_label = Label(limit_frame, text="Giới hạn: ")
limit_result_label.grid(row = 5, column = 3)

# Khởi chạy giao diện
root.mainloop()
